##### Set path for input data 
output_fold: VCF_test
vcf_file: VCF_example_data/example_mutect2.vcf
sample_name: test
hla_str: HLA-A02:01
expression_file: VCF_example_data/example_abundance.tsv
copynumber_profile: VCF_example_data/example_seg_copynumber.txt
tumor_cellularity: 0.33
peptide_length: 9

##### Some filters parameter
tumor_depth_cutoff: 7
tumor_vaf_cutoff: 0.05
normal_vaf_cutoff: 0.03
binding_fc_aff_cutoff: 1
binding_aff_cutoff: 2
fpkm_cutoff: 0

##### specify other software excutable path in your system as you have installed them.
vep_cache_path: your/path/to/vep_cache_data/
vep_path: your/path/to/vep
netMHCpan_path: your/path/to/netMHCpan
pyclone_path: your/path/to/PyClone
